### ISSUE TITLE
Booting Issue

### ISSUE THREAD

**Issue by mauronofrio** [IcemanDev/android_device_xiaomi_perseus#1]
Ciao, mi sto mettendo a lavoro anche io su questo mix 3, ho visto questo tuo progetto per la twrp, volevo chiederti di collaborare per sistemare la TWRP per mix 3. Non sono riuscito a contattarti da nessun'altra parte, ovviamente sarebbe meglio parlare su una qualche chat tipo telegram o hangouts. Il mio principale problema è far avviare la twrp. Se vuoi contattami su telegram il nick è sempre lo stesso

**Comment by IcemanDev** [comment]
Ciao. Si, effettivamente avevo dato inizio a questo progetto con l'ausilio
di un valido beta-tester. Sin dai primi passaggi la twrp è venuta fuori.
Purtroppo ho lavorato sempre "al buio" non essendo in possesso del device e
ciò ha molto penalizzato la buona riuscita. Io lavoro con codice ufficiale
TWRP. Da quel che ho potuto verificare la TWRP cosiddetta "cinese" è venuta
fuori da un codice modificato che, come molti utenti hanno potuto
constatare, non funziona per niente bene... o meglio non funziona come
dovrebbe una TWRP degna del nome.
Come accennato, io non sono in possesso del Mix3 onte per cui non ho la
possibilità di effettuare test diretti.
Se è tua buona intenzione proseguire il progetto posso darti qualche
appoggio... ma tieni presente che non sono in possesso del Mix3.
Oltre che su GitHub scrivo su un forum spagnolo www.movilesdualsim.com (mio
nick Iceman-IT)


Il giorno sab 23 feb 2019 alle ore 12:11 mauronofrio matarrese <
notifications@github.com> ha scritto:

**Comment by mauronofrio** [comment]
Grazie della risposta, anche io lavoro molto sulle twrp ufficiali e ne ho fatte molte nell'ultimo periodo. Attualmente ho qualche problema nel far avviare la TWRP, ho trovato il tuo tester e mi ha detto che la tua twrp a volte si avviava, vorrei recuperare quel codice e sistemarlo per farlo funzionare anche per la decriptazione. Se mi potessi dare una mano in questo poi vedrei io come far funzionare la decryptazione.

**Comment by IcemanDev** [comment]
Ho utilizzato la build PQ1A.181105.017.A1. Ovviamente il deltree l'ho
approntato io ma deve essere messo a punto secondo il prosieguo dei tests.
 deltree_xiaomi.tar
<https://drive.google.com/file/d/1-YEdImIK0YU-0BfEY37QfCJ-gQZXRV4N/view?usp=drive_web>

Il giorno sab 23 feb 2019 alle ore 17:52 mauronofrio matarrese <
notifications@github.com> ha scritto:

**Comment by mauronofrio** [comment]
Questa twrp dovrebbe avviarsi giusto?

**Comment by IcemanDev** [comment]
Per quel che ricordo dovrebbe partire. Considera che sono stati fatti
decine di test con aggiustamenti in corsa

Il sab 23 feb 2019, 19:24 mauronofrio matarrese <notifications@github.com>
ha scritto:

**Comment by mauronofrio** [comment]
Alla fine è uscita una buona twrp, il mio sorgente era quasi pronto, dovevo solo togliere due file.
Grazie dell'aiuto

**Comment by IcemanDev** [comment]
Bene. Son contento.

Il ven 8 mar 2019, 21:19 mauronofrio matarrese <notifications@github.com>
ha scritto:
